name:                aoc23
version:             0.1.0.0
github:              "tobeannouncd/AdventOfCode2023"
license:             MIT
author:              "tobeannouncd"
maintainer:          "wzrds3@gmail.com"
copyright:           "2023 Tyler Aas"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tobeannouncd/AdventOfCode2023#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- parsec
- array
- fingertree
- mtl
- ordered-containers

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc23-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc23
    - advent-of-code-api
    - time
    - tz

tests:
  aoc23-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc23
    - hspec
